Analysis:
  process_2:
    name: 'taper'
    method: 'hann'
    max_percentage: 0.05
  process_3:
    name: 'rmean'
    method: 'simple'
  process_3:
    name: 'normalize'
    norm:
  process_4:
    name: 'differentiate'
    diff: true
  process_5:
    name: 'integrate'
    method: 'spline'
  process_6:
    name: 'filter'
    method: 'bandpass'
    freqmin: 4.0
    freqmax: 8.0
  process_7:
    name: 'wiener_filter'
    time_window: 0
    noise_power: 0
  process_8:
    name: 'remove_response'
    inventory: '/home/sysop/Escritorio/geofisica/ISP/isp/Metadata/xml/metadata.xml'
    water_level: 0
    units: 'Wood Anderson'
    pre_filt: [1,2,3,4]
  process_9:
    name: 'add_white_noise'
    SNR_dB: 10
  process_10:
    name: 'whitening'
    freq_width: 0.04
    taper_edge: True
  process_11:
    name: 'remove_spikes'
    window_size: 10
    n: 4
  process_12:
    name: 'time_normalization'
    method: '1bit'
    norm_win: 10
  process_13:
    name: 'wavelet_denoise'
    dwt: 'db2'
    threshold: 0.5
  process_14:
    name: 'resample'
    pre_filter: True
    sampling_rate: 100
  process_15:
    name: 'fill_gaps'
    method: 'interpolate'
  process_16:
    name: 'smoothing'
    method: 'gaussian'
    time_window: 5
    FWHM: 0.05
