Analysis:
  process_1:
    name: 'kurtosis'
    CF_decay_win: 4.0
    fmin: 0.5
    fmax: 8.5

#  process_1:
#    name: 'envelope'
#    method: 'SMOOTH'
#    corner_freq: 0.15

#  process_1:
#    name: 'envelope'
#    method: 'SMOOTH'
#    corner_freq: 0.15

# process_1:
#    name: 'snr'
#    method: 'classic'
#    sign_win: 1
#    noise_win: 40

#  process_1:
#    name: 'entropy'
#    win: 5.0
#    overlap: 50