Analysis:
  process_1:
    name: 'fill_gaps'
    method: 'latest'
  process_2:
    name: 'rmean'
    method: 'linear'
  process_3:
    name: 'taper'
    method: 'cosine'
    max_percentage: 0.05
  process_4:
    name: 'filter'
    type: 'bandpass'
    fmin: 0.5
    fmax: 12.0
    corners: 4
    zerophase: True
  process_5:
    name: 'cross_correlate'
    mode: 'full'
    normalize: 'full'
    reference_idx: 0
    strict: True
    trim: True

